### ISSUE TITLE
Writeup Slack dialogs and link from Workbot connector

### ISSUE THREAD

**Issue by huilinn** [workato/docs#282] opened 2017-10-20 01:26 UTC

**Comment by jandonyada** [comment] 2018-03-12 01:28
Hey @huilinn can I take this on? Will need a bit of context - hope to ask in person!

**Comment by huilinn** [comment] 2018-03-12 21:20
Yup, sounds good! Have reassigned

**Comment by jandonyada** [comment] 2018-03-13 04:00
![image](https://user-images.githubusercontent.com/14304570/37317729-ca026d24-2623-11e8-96d3-b30177863ae9.png)
- To write the content for the dialog hint.
- Link the 'Learn More' to Dialogs doc (to be drafted)

**Comment by jandonyada** [comment] 2018-03-13 05:28
Closing this as it is a duplicate of https://github.com/workato/issues/issues/6239

**Closed** 2018-03-13 05:28 UTC
Labels: content
